apiVersion: apps/v1
kind: Deployment
metadata:
  name: minio
  namespace: kubeflow
spec:
  template:
    spec:
      containers:
        - name: minio
          image: minio/minio:RELEASE.2023-03-20T20-16-18Z
          resources:
            requests:
              cpu: 200m        # Reduced from upstream 500m because we use smaller nodes
              memory: 256Mi    # Reduced from upstream 1Gi because we use smaller nodes
            limits:
              cpu: 500m
              memory: 512Mi
