apiVersion: apps/v1
kind: Deployment
metadata:
  name: ml-pipeline-ui
  namespace: kubeflow
spec:
  template:
    spec:
      containers:
        - name: ml-pipeline-ui
          image: dhi.io/kubeflow-pipelines-frontend:2-debian13-dev
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 200m
              memory: 256Mi
