# JupyterHub 3.3.7 — Minimal demo configuration

hub:
  resources:
    requests:
      cpu: 200m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi

  service:
    type: ClusterIP

proxy:
  service:
    type: LoadBalancer
  chp:
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 200m
        memory: 256Mi

singleuser:
  image:
    name: jupyter/scipy-notebook
    tag: "latest"

  cpu:
    limit: 1

  memory:
    limit: 1G

  storage:
    capacity: 1Gi
    storageClassName: gp3-ebs
